version: '3.8'

services:
  app:
    build:
      context: containers/app
    image: helloworld_ros_melodic_gazebo9_app:latest
    user: robomaker
    environment:
      #- DISPLAY=host.docker.internal:0  # For macOS
      - DISPLAY
      - XAUTHORITY=/root/.Xauthority 
      - ROBOMAKER_GAZEBO_MASTER_URI=http://localhost:5555
      - ROBOMAKER_ROS_MASTER_URI=http://localhost:11311
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
  sim:
    build:
      context: containers/sim
    image: helloworld_ros_melodic_gazebo9_simulator:latest
    user: robomaker
    environment:
      #- DISPLAY=host.docker.internal:0  # For macOS
      - DISPLAY
      - XAUTHORITY=/root/.Xauthority 
      - ROBOMAKER_GAZEBO_MASTER_URI=http://localhost:5555
      - ROBOMAKER_ROS_MASTER_URI=http://localhost:11311
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
